export type DesignFamily = {
  id: string
  name: string
  navigation: string
  hero: string
  composition: string
  typography: string
  spacing: string
  cards: string
  borders: string
  background: string
  motion: string
  mobile: string
  footer: string
}

function family(id: string, name: string, values: Omit<DesignFamily, "id" | "name">): DesignFamily {
  return { id, name, ...values }
}

export const DESIGN_FAMILIES: readonly DesignFamily[] = [
  family("aurora-console", "Aurora Console", {
    navigation: "compact floating command bar",
    hero: "split hero with an illuminated product console",
    composition: "asymmetric technical grid",
    typography: "geometric sans with precise mono accents",
    spacing: "dense controls inside generous section rhythm",
    cards: "deep glass panels with layered status surfaces",
    borders: "fine cyan and violet illuminated edges",
    background: "dark aurora mesh with a subtle engineering grid",
    motion: "slow aurora drift, status pulses and restrained panel lift",
    mobile: "stacked console with a bottom command dock",
    footer: "compact system-status footer",
  }),
  family("editorial-luxe", "Editorial Luxe", {
    navigation: "minimal wordmark navigation",
    hero: "oversized editorial headline with offset imagery",
    composition: "magazine columns and intentional overlap",
    typography: "high-contrast serif paired with clean sans",
    spacing: "large cinematic whitespace",
    cards: "borderless editorial story blocks",
    borders: "hairline metallic separators",
    background: "warm paper gradient with soft light pools",
    motion: "masked text reveals and gentle image parallax",
    mobile: "single-column editorial sequence",
    footer: "large typographic closing statement",
  }),
  family("kinetic-gradient", "Kinetic Gradient", {
    navigation: "colour-shifting pill navigation",
    hero: "kinetic type surrounding a dimensional focal object",
    composition: "layered diagonal sections",
    typography: "bold grotesk with gradient emphasis",
    spacing: "energetic alternating compression and release",
    cards: "soft rounded colour fields",
    borders: "translucent chromatic rims",
    background: "animated multi-colour mesh",
    motion: "gradient travel, cursor glow and spring-like hover lift",
    mobile: "vertical colour narrative with thumb-friendly actions",
    footer: "full-width animated colour band",
  }),
  family("monochrome-grid", "Monochrome Grid", {
    navigation: "strict horizontal utility navigation",
    hero: "type-led hero aligned to a visible grid",
    composition: "modular Swiss grid",
    typography: "neo-grotesk with mono metadata",
    spacing: "systematic eight-point rhythm",
    cards: "square modular tiles",
    borders: "high-contrast one-pixel rules",
    background: "off-white or near-black graph paper",
    motion: "precise wipes and grid-aware transitions",
    mobile: "single-column modules preserving grid labels",
    footer: "indexed sitemap grid",
  }),
  family("soft-sculpture", "Soft Sculpture", {
    navigation: "floating translucent capsule",
    hero: "central sculptural form with orbiting benefits",
    composition: "organic radial composition",
    typography: "friendly rounded sans",
    spacing: "airy and calm",
    cards: "clay-like raised surfaces",
    borders: "soft inner highlights without hard outlines",
    background: "pastel atmospheric gradient",
    motion: "slow float, orbit and soft press interactions",
    mobile: "stacked tactile cards with reduced orbit motion",
    footer: "rounded multi-column tray",
  }),
  family("midnight-finance", "Midnight Finance", {
    navigation: "secure compact finance header",
    hero: "trust-led split hero with live financial data",
    composition: "disciplined dashboard hierarchy",
    typography: "confident sans with tabular numerals",
    spacing: "compact data density with clear grouping",
    cards: "dark ledger panels with inset metrics",
    borders: "subtle navy rules with cyan confirmation states",
    background: "midnight navy with restrained market glow",
    motion: "number transitions, chart reveals and security pulses",
    mobile: "priority metrics first with horizontally scrollable detail",
    footer: "compliance and trust footer",
  }),
  family("natural-calm", "Natural Calm", {
    navigation: "light organic navigation with rounded actions",
    hero: "human-centred image hero with calm supporting copy",
    composition: "soft alternating content bands",
    typography: "humanist sans with warm serif accents",
    spacing: "relaxed breathing room",
    cards: "paper-like rounded cards",
    borders: "warm low-contrast outlines",
    background: "cream, sage and sunlit texture",
    motion: "gentle fades and natural drift",
    mobile: "simple vertical flow with persistent primary action",
    footer: "warm community-focused footer",
  }),
  family("brutalist-signal", "Brutalist Signal", {
    navigation: "bold boxed navigation",
    hero: "oversized statement with raw utility controls",
    composition: "hard-edged offset blocks",
    typography: "heavy condensed display with mono labels",
    spacing: "deliberate abrupt scale changes",
    cards: "flat high-contrast slabs",
    borders: "thick black or fluorescent rules",
    background: "solid signal colour with raw grid marks",
    motion: "snaps, hard slides and marquee signals",
    mobile: "stacked poster panels",
    footer: "oversized contact strip",
  }),
  family("glass-orbit", "Glass Orbit", {
    navigation: "circular glass navigation cluster",
    hero: "orbital product story around a glass core",
    composition: "concentric layers and floating satellites",
    typography: "sleek extended sans",
    spacing: "wide orbital spacing",
    cards: "transparent lens-like cards",
    borders: "refractive gradient rings",
    background: "deep space colour field",
    motion: "slow orbital rotation and depth-aware hover",
    mobile: "linear orbit story with static depth cues",
    footer: "circular call-to-action and minimal links",
  }),
  family("bento-operator", "Bento Operator", {
    navigation: "workspace rail plus contextual top bar",
    hero: "immediate operational overview",
    composition: "responsive bento control grid",
    typography: "compact product sans with mono values",
    spacing: "efficient consistent gutters",
    cards: "mixed-size functional bento modules",
    borders: "quiet functional separators",
    background: "neutral application canvas",
    motion: "module expansion and live-status updates",
    mobile: "priority-ordered bento stack",
    footer: "small product and system links",
  }),
  family("cinematic-product", "Cinematic Product", {
    navigation: "transparent cinematic header",
    hero: "full-bleed visual scene with anchored product message",
    composition: "scrolling chapters with immersive media",
    typography: "large cinematic sans",
    spacing: "full-viewport pacing",
    cards: "minimal floating information panels",
    borders: "nearly invisible glass edges",
    background: "image-led dark cinematic environment",
    motion: "depth parallax, reveal masks and light sweeps",
    mobile: "cropped cinematic scenes with readable overlays",
    footer: "dark credits-style footer",
  }),
  family("retro-future", "Retro Future", {
    navigation: "instrument-panel navigation",
    hero: "retro terminal headline with futuristic product visual",
    composition: "console bands and information readouts",
    typography: "wide display face with pixel or mono details",
    spacing: "technical compact rhythm",
    cards: "screen-like panels with corner hardware",
    borders: "double-line neon instrument frames",
    background: "dark scanline gradient with luminous horizon",
    motion: "scan sweeps, cursor ticks and controlled flicker",
    mobile: "single instrument column",
    footer: "terminal sign-off panel",
  }),
  family("warm-commerce", "Warm Commerce", {
    navigation: "category-led retail navigation",
    hero: "product-and-lifestyle merchandising hero",
    composition: "shoppable editorial sections",
    typography: "warm display serif with practical sans",
    spacing: "comfortable retail rhythm",
    cards: "image-forward product cards",
    borders: "soft neutral dividers",
    background: "warm neutral canvas with seasonal accents",
    motion: "product image swap, cart feedback and gentle hover",
    mobile: "two-column product grid and sticky cart action",
    footer: "service, delivery and trust columns",
  }),
  family("precision-health", "Precision Health", {
    navigation: "clear accessible service navigation",
    hero: "reassuring clinical hero with immediate next action",
    composition: "structured care pathways",
    typography: "high-legibility humanist sans",
    spacing: "calm accessible spacing",
    cards: "clean clinical information cards",
    borders: "soft blue-green accessible outlines",
    background: "bright clean field with subtle biological forms",
    motion: "calm progress and confirmation transitions",
    mobile: "large touch targets and simplified care flow",
    footer: "contact, accreditation and emergency information",
  }),
  family("playful-modular", "Playful Modular", {
    navigation: "colour-coded modular navigation",
    hero: "friendly illustrated modular hero",
    composition: "stacked playful building blocks",
    typography: "expressive rounded display with clear body text",
    spacing: "bouncy varied rhythm",
    cards: "colourful sticker-like modules",
    borders: "bold rounded outlines",
    background: "light canvas with abstract shapes",
    motion: "small bounce, wiggle and reveal interactions",
    mobile: "large stacked modules with reduced decoration",
    footer: "friendly illustrated link garden",
  }),
  family("architectural-space", "Architectural Space", {
    navigation: "quiet edge-aligned navigation",
    hero: "spatial hero with strong image geometry",
    composition: "architectural planes and measured asymmetry",
    typography: "refined modern sans with narrow captions",
    spacing: "gallery-scale whitespace",
    cards: "frameless project plates",
    borders: "precise hairline construction rules",
    background: "stone, concrete and daylight tones",
    motion: "measured pans and sectional reveals",
    mobile: "vertical project gallery",
    footer: "studio index and contact plate",
  }),
  family("data-spectrum", "Data Spectrum", {
    navigation: "analytics command header",
    hero: "data narrative with a spectrum visualization",
    composition: "chart-led analytical canvas",
    typography: "technical sans with tabular numerals",
    spacing: "dense but grouped analytical rhythm",
    cards: "layered metric and chart panels",
    borders: "spectrum-coded data separators",
    background: "dark neutral canvas with spectral highlights",
    motion: "progressive chart drawing and filter transitions",
    mobile: "summary-first analytics stack",
    footer: "data sources and status footer",
  }),
  family("craft-paper", "Craft Paper", {
    navigation: "handmade label navigation",
    hero: "story-led craft hero with tactile imagery",
    composition: "scrapbook layers and irregular columns",
    typography: "character serif with handwritten accents",
    spacing: "human irregular rhythm",
    cards: "paper labels and pinned notes",
    borders: "ink rules and torn-paper edges",
    background: "textured paper and natural pigment",
    motion: "subtle paper slide and stamp feedback",
    mobile: "clean scrapbook stack",
    footer: "maker story and contact card",
  }),
  family("neon-nightlife", "Neon Nightlife", {
    navigation: "dark floating event navigation",
    hero: "high-energy event poster hero",
    composition: "layered posters and schedule bands",
    typography: "compressed display with luminous accents",
    spacing: "tight high-energy rhythm",
    cards: "glowing ticket and event panels",
    borders: "electric gradient outlines",
    background: "black club atmosphere with coloured haze",
    motion: "light sweeps, equalizer pulses and ticket hover",
    mobile: "schedule-first event stack",
    footer: "venue, social and ticket strip",
  }),
  family("quiet-enterprise", "Quiet Enterprise", {
    navigation: "comprehensive restrained enterprise header",
    hero: "outcome-led enterprise split hero",
    composition: "clear evidence and capability sections",
    typography: "neutral professional sans",
    spacing: "generous predictable hierarchy",
    cards: "structured proof and capability cards",
    borders: "subtle cool-grey rules",
    background: "light neutral canvas with restrained brand tint",
    motion: "minimal fades and diagram progression",
    mobile: "clear decision-focused sequence",
    footer: "detailed enterprise sitemap",
  }),
  family("liquid-metal", "Liquid Metal", {
    navigation: "minimal chrome-edged navigation",
    hero: "metallic dimensional object and reflective type",
    composition: "fluid layers around sharp product content",
    typography: "sharp contemporary display sans",
    spacing: "dramatic open space",
    cards: "dark polished metal plates",
    borders: "chrome gradient rims",
    background: "liquid metal reflections over deep colour",
    motion: "specular light travel and slow fluid morph",
    mobile: "simplified reflective layers with static highlights",
    footer: "polished closing plate",
  }),
] as const

function hash(value: string): number {
  let result = 2166136261
  for (let index = 0; index < value.length; index += 1) {
    result ^= value.charCodeAt(index)
    result = Math.imul(result, 16777619)
  }
  return result >>> 0
}

export function selectDesignFamily(seed: string, requestedDirection: string[]): DesignFamily {
  const direction = requestedDirection.join("|")
  return DESIGN_FAMILIES[hash(`${seed}|${direction}`) % DESIGN_FAMILIES.length]
}

export function designFamilyBrief(value: DesignFamily): string[] {
  return [
    `Design family: ${value.name} (${value.id})`,
    `Navigation: ${value.navigation}`,
    `Hero: ${value.hero}`,
    `Page composition: ${value.composition}`,
    `Typography: ${value.typography}`,
    `Spacing: ${value.spacing}`,
    `Card geometry: ${value.cards}`,
    `Border system: ${value.borders}`,
    `Background: ${value.background}`,
    `Motion: ${value.motion}`,
    `Mobile layout: ${value.mobile}`,
    `Footer: ${value.footer}`,
  ]
}
