export type DesignFamily = {
  id: string
  name: string
  aliases: string[]
  navigation: string
  hero: string
  composition: string
  sectionOrder: string
  typography: string
  palette: string
  spacing: string
  cards: string
  buttons: string
  forms: string
  borders: string
  background: string
  motion: string
  effects3d: string
  mobile: string
  interactions: string
  footer: string
}

function family(value: DesignFamily): DesignFamily {
  return value
}

export const DESIGN_FAMILIES: readonly DesignFamily[] = [
  family({
    id: "apple-minimal",
    name: "Apple Minimal",
    aliases: ["apple", "apple style", "product minimal"],
    navigation: "translucent centred product navigation that compresses on scroll",
    hero: "single iconic product statement with a large isolated visual",
    composition: "full-viewport product chapters alternating copy and media",
    sectionOrder: "statement, product reveal, benefits, detail gallery, comparison, final call to action",
    typography: "large neutral sans headlines with compact high-legibility body copy",
    palette: "white, graphite and one restrained product accent",
    spacing: "cinematic whitespace with tightly controlled text measures",
    cards: "borderless media stages and softly rounded feature trays",
    buttons: "small solid primary pills and quiet text-arrow actions",
    forms: "minimal underlined fields with inline validation",
    borders: "almost invisible cool-grey separators",
    background: "clean light fields with occasional near-black product chapters",
    motion: "scroll-bound product reveals, gentle scale and masked transitions",
    effects3d: "photoreal product depth without decorative floating objects",
    mobile: "edge-to-edge product story with a compact sticky action",
    interactions: "chapter progress, comparison toggles and restrained media scrub",
    footer: "dense product sitemap on a neutral field",
  }),
  family({
    id: "stripe-saas",
    name: "Stripe SaaS",
    aliases: ["stripe", "stripe style", "fintech gradient"],
    navigation: "multi-level SaaS navigation with a rounded sign-in and primary action",
    hero: "asymmetric conversion hero paired with live product UI",
    composition: "angled colour bands, proof strips and alternating product narratives",
    sectionOrder: "value proposition, product demo, customer proof, platform modules, integrations, conversion",
    typography: "confident grotesk with compact technical labels",
    palette: "indigo, violet, cyan and warm highlight gradients",
    spacing: "dense information islands separated by generous diagonal transitions",
    cards: "layered product panels with mixed radii and tinted surfaces",
    buttons: "high-contrast pills with arrow motion and secondary text actions",
    forms: "compact labelled controls inside elevated product panels",
    borders: "tinted one-pixel dividers and subtle inner rings",
    background: "light canvas crossed by controlled gradient meshes",
    motion: "gradient travel, diagram progression and directional hover shifts",
    effects3d: "perspective-stacked dashboard panels",
    mobile: "linear conversion story with horizontally scrollable proof",
    interactions: "product tabs, animated metrics and integration explorer",
    footer: "deep multi-column platform footer",
  }),
  family({
    id: "framer-creative",
    name: "Framer Creative",
    aliases: ["framer", "creative agency", "experimental creative"],
    navigation: "floating creative toolbar with playful state changes",
    hero: "kinetic type composed around interactive artwork",
    composition: "overlapping canvases, irregular grids and scroll chapters",
    sectionOrder: "manifesto, featured work, capabilities, process, selected clients, contact",
    typography: "expressive variable display type paired with a disciplined sans",
    palette: "high-energy complementary colour fields with black and white anchors",
    spacing: "intentional tension between compressed clusters and oversized gaps",
    cards: "art-directed project tiles with independently varied geometry",
    buttons: "magnetic labels, circular actions and oversized contact controls",
    forms: "editorial form layout with animated focus states",
    borders: "selective bold rules and chromatic frames",
    background: "layered colour canvas with masks and grain",
    motion: "kinetic typography, cursor response, springs and image reveals",
    effects3d: "tilting project planes and depth-stacked artwork",
    mobile: "single creative reel with reduced-motion equivalents",
    interactions: "drag galleries, project filters and responsive cursor scenes",
    footer: "oversized animated contact statement",
  }),
  family({
    id: "vercel-monochrome",
    name: "Vercel Monochrome",
    aliases: ["vercel", "monochrome", "developer platform"],
    navigation: "strict black-and-white developer header with command shortcuts",
    hero: "grid-aligned developer proposition with terminal or deployment proof",
    composition: "precise modular grid with technical diagrams",
    sectionOrder: "headline, deployment proof, platform grid, workflow, metrics, documentation action",
    typography: "neutral sans with mono code and metadata",
    palette: "black, white and cool greys with sparse status colour",
    spacing: "systematic eight-point rhythm and strong baseline alignment",
    cards: "square technical modules with shared grid borders",
    buttons: "black or white compact rectangles with exact focus rings",
    forms: "command-like inputs and restrained control groups",
    borders: "high-contrast one-pixel grid rules",
    background: "clean field with subtle graph or radial light",
    motion: "precise wipes, typing states and grid-aware transitions",
    effects3d: "flat technical depth using stacked planes only",
    mobile: "single-column modules preserving code readability",
    interactions: "command palette, copy actions and live deployment states",
    footer: "indexed developer sitemap",
  }),
  family({
    id: "luxury-vvip",
    name: "Luxury VVIP",
    aliases: ["luxury", "vvip", "black and gold", "premium"],
    navigation: "minimal wordmark navigation with discreet concierge action",
    hero: "dramatic art-directed statement with exclusive imagery",
    composition: "cinematic editorial panels and measured asymmetry",
    sectionOrder: "brand statement, signature offering, provenance, private service, testimonial, enquiry",
    typography: "high-contrast display serif with elegant uppercase sans labels",
    palette: "obsidian, ivory, champagne gold and one jewel tone",
    spacing: "gallery-scale whitespace and slow visual pacing",
    cards: "frameless image stories and refined inset service plates",
    buttons: "thin metallic outlines and dark filled concierge actions",
    forms: "private-enquiry forms with generous fields and elegant labels",
    borders: "hairline metallic separators",
    background: "deep tonal fields with soft directional light",
    motion: "slow masked reveals, image parallax and specular sweeps",
    effects3d: "subtle embossed surfaces and photographic depth",
    mobile: "luxury editorial sequence with persistent concierge access",
    interactions: "lookbook viewer, service selector and private enquiry flow",
    footer: "minimal legal and concierge closing panel",
  }),
  family({
    id: "editorial-magazine",
    name: "Editorial Magazine",
    aliases: ["editorial", "magazine", "newspaper"],
    navigation: "issue-led masthead with section index",
    hero: "cover-story headline with offset photography and metadata",
    composition: "multi-column reading grid with pull quotes and side notes",
    sectionOrder: "lead story, latest grid, feature essay, topics, contributors, newsletter",
    typography: "display serif, readable text serif and utilitarian sans metadata",
    palette: "paper white, ink black and one issue-specific editorial colour",
    spacing: "text-led rhythm with deliberate column gutters",
    cards: "article teasers rather than generic product cards",
    buttons: "underlined reading actions and compact subscription controls",
    forms: "publication-style newsletter and search fields",
    borders: "ink rules of varied weights",
    background: "warm paper with optional print grain",
    motion: "headline masks, page-like reveals and subtle image pans",
    effects3d: "paper stacking and cover depth only",
    mobile: "single reading column with sticky issue navigation",
    interactions: "topic filters, reading progress and expandable annotations",
    footer: "publication index, archive and colophon",
  }),
  family({
    id: "glassmorphism",
    name: "Glassmorphism",
    aliases: ["glassmorphism", "glass", "frosted"],
    navigation: "floating frosted capsule with luminous active states",
    hero: "central translucent product core surrounded by supporting lenses",
    composition: "layered depth planes over an atmospheric scene",
    sectionOrder: "glass hero, capability orbit, interactive demo, trust layer, plans, action",
    typography: "sleek extended sans with bright contrast",
    palette: "deep indigo, cyan, violet and translucent white",
    spacing: "wide orbital gaps with compact content inside panels",
    cards: "frosted lenses with varied blur and opacity",
    buttons: "luminous glass pills with inner highlights",
    forms: "translucent fields with strong accessible focus treatment",
    borders: "refractive gradient rings",
    background: "deep atmospheric mesh with controlled light blooms",
    motion: "slow orbit, depth-aware hover and moving refraction",
    effects3d: "layered glass planes with perspective and soft shadows",
    mobile: "linear glass stack with reduced blur for performance",
    interactions: "depth tilt, segmented glass controls and orbit navigation",
    footer: "minimal translucent closing tray",
  }),
  family({
    id: "cyberpunk-neon",
    name: "Cyberpunk Neon",
    aliases: ["cyberpunk", "neon", "retro future", "gaming"],
    navigation: "instrument-panel navigation with status readouts",
    hero: "terminal statement and luminous system visualization",
    composition: "console bands, diagonal signals and dense readout zones",
    sectionOrder: "system boot, mission, modules, live feed, access tiers, connect",
    typography: "wide futuristic display face with mono telemetry",
    palette: "near-black, electric cyan, magenta and acid signal accents",
    spacing: "compact technical rhythm interrupted by large signal moments",
    cards: "screen panels with clipped corners and hardware details",
    buttons: "neon command controls with tactile active states",
    forms: "terminal inputs, scan indicators and explicit validation",
    borders: "double-line luminous instrument frames",
    background: "scanline city haze with engineering grid",
    motion: "scan sweeps, controlled glitch, cursor ticks and status pulses",
    effects3d: "perspective HUD layers and holographic depth",
    mobile: "single instrument column with bottom command dock",
    interactions: "live console filters, command entry and alert acknowledgement",
    footer: "terminal sign-off and network status",
  }),
  family({
    id: "industrial-control",
    name: "Industrial Control Room",
    aliases: ["industrial", "control room", "factory kiosk", "warehouse"],
    navigation: "persistent operations rail plus status top bar",
    hero: "operational command overview rather than marketing hero",
    composition: "dense control grid prioritising alarms and production state",
    sectionOrder: "critical alerts, line status, output KPIs, maintenance, resources, shift log",
    typography: "high-legibility industrial sans with tabular mono values",
    palette: "graphite, steel, safety amber, status green and alarm red",
    spacing: "touch-safe compact density with strong grouping",
    cards: "rugged telemetry panels and equipment modules",
    buttons: "large labelled control actions with safety hierarchy",
    forms: "operator forms designed for gloves, scanners and fast entry",
    borders: "strong functional separators and status rails",
    background: "dark anti-glare canvas with technical grid",
    motion: "live state transitions, alarm pulses and equipment flow",
    effects3d: "schematic machine depth, never decorative perspective",
    mobile: "field status list with priority alarms first",
    interactions: "alarm acknowledgement, line drill-down and shift handover",
    footer: "plant status, time, connectivity and operator identity",
  }),
  family({
    id: "medical-clean",
    name: "Medical Clean",
    aliases: ["medical", "clinic", "healthcare", "dental"],
    navigation: "accessible service navigation with urgent contact visibility",
    hero: "reassuring care proposition and immediate booking action",
    composition: "clear care pathways with human proof and clinical trust",
    sectionOrder: "care promise, services, clinicians, patient pathway, evidence, booking",
    typography: "high-legibility humanist sans with gentle display accents",
    palette: "clean white, calm blue-green and warm human accent",
    spacing: "calm accessible spacing with large touch targets",
    cards: "clean care cards with meaningful icons and clear hierarchy",
    buttons: "high-contrast rounded booking and contact controls",
    forms: "accessible labelled patient forms with privacy guidance",
    borders: "soft blue-green outlines",
    background: "bright clinical field with subtle biological geometry",
    motion: "calm progress, confirmation and gentle content reveals",
    effects3d: "soft anatomical or service illustrations only",
    mobile: "booking-first flow with persistent call action",
    interactions: "appointment selection, service finder and FAQ disclosure",
    footer: "contact, accreditation, accessibility and emergency information",
  }),
  family({
    id: "education-colour",
    name: "Education Colour",
    aliases: ["education", "school", "children", "learning"],
    navigation: "role-aware colourful navigation with large friendly targets",
    hero: "welcoming learning story with illustrated activity",
    composition: "modular learning path and community highlights",
    sectionOrder: "welcome, programmes, learning journey, achievements, community, enrolment",
    typography: "expressive rounded display with highly readable body copy",
    palette: "optimistic primary colours balanced by warm neutral space",
    spacing: "bouncy varied rhythm while preserving accessibility",
    cards: "colour-coded subject and activity modules",
    buttons: "friendly rounded actions with clear icon cues",
    forms: "step-by-step enrolment fields with supportive instructions",
    borders: "bold rounded outlines and sticker accents",
    background: "light canvas with purposeful illustrated shapes",
    motion: "small bounce, progress celebrations and playful reveals",
    effects3d: "soft toy-like illustrations with restrained depth",
    mobile: "large stacked learning modules and bottom role navigation",
    interactions: "programme explorer, progress steps and calendar activities",
    footer: "friendly contact, safeguarding and community link garden",
  }),
  family({
    id: "restaurant-elegant",
    name: "Restaurant Elegant",
    aliases: ["restaurant", "cafe", "dining", "food"],
    navigation: "reservation-led header with menu and location access",
    hero: "full sensory dish or dining-room scene with concise story",
    composition: "editorial menu moments alternating with atmosphere",
    sectionOrder: "experience, signature menu, chef story, gallery, reviews, reservation",
    typography: "warm display serif paired with practical menu sans",
    palette: "seasonal food tones, cream, charcoal and a refined accent",
    spacing: "comfortable hospitality rhythm with image-led pauses",
    cards: "menu plates, event stories and reservation panels",
    buttons: "elegant reservation fills and understated menu links",
    forms: "date, party-size and time controls optimised for fast booking",
    borders: "soft neutral dividers and fine menu rules",
    background: "warm tactile canvas with dark atmospheric chapters",
    motion: "dish reveals, gallery pans and reservation confirmation",
    effects3d: "photographic table depth without floating UI decoration",
    mobile: "menu-first layout with sticky reserve and call controls",
    interactions: "menu filters, gallery viewer and reservation availability",
    footer: "hours, location, dietary information and social proof",
  }),
  family({
    id: "manufacturing-operations",
    name: "Manufacturing Operations",
    aliases: ["manufacturing", "production", "food production", "factory management"],
    navigation: "module rail for production, quality, stock, maintenance and reports",
    hero: "shift command centre with output, downtime and quality exceptions",
    composition: "role-based operational dashboard with traceable work queues",
    sectionOrder: "shift health, active lines, quality holds, materials, maintenance, traceability",
    typography: "compact industrial sans with tabular batch and machine values",
    palette: "steel, navy, process blue, safety amber and quality green",
    spacing: "high information density with touch-safe operator controls",
    cards: "line, batch, machine and inventory modules with status hierarchy",
    buttons: "operational actions separated from destructive and safety actions",
    forms: "scanner-ready batch, inspection and material-entry workflows",
    borders: "functional separators keyed to production state",
    background: "anti-glare plant canvas with restrained schematic texture",
    motion: "live production counters, line flow and exception transitions",
    effects3d: "factory topology and line schematic depth",
    mobile: "technician jobs, scanning and alerts in a bottom-tab shell",
    interactions: "batch drill-down, barcode scan, inspection sign-off and downtime logging",
    footer: "plant, shift, sync, audit and connectivity status",
  }),
  family({
    id: "saas-dashboard",
    name: "SaaS Dashboard",
    aliases: ["saas dashboard", "admin dashboard", "crm", "erp", "customer portal"],
    navigation: "collapsible workspace rail with contextual command header",
    hero: "immediate product overview with actionable onboarding or KPIs",
    composition: "responsive bento workspace tuned to user role",
    sectionOrder: "priority actions, KPIs, work queue, activity, insights, configuration",
    typography: "compact product sans with tabular values and mono IDs",
    palette: "neutral application canvas with tenant-configurable accent",
    spacing: "efficient consistent gutters and dense control groups",
    cards: "mixed-size functional bento modules",
    buttons: "clear primary, secondary, icon and destructive action hierarchy",
    forms: "labelled product controls with validation and autosave states",
    borders: "quiet functional separators",
    background: "neutral workspace canvas with subtle depth",
    motion: "module expansion, optimistic updates and live-status transitions",
    effects3d: "flat application depth using elevation only",
    mobile: "priority dashboard stack with bottom tabs",
    interactions: "filters, saved views, command search, bulk actions and drawers",
    footer: "small product, privacy and system-status links",
  }),
  family({
    id: "iot-command-centre",
    name: "IoT Command Centre",
    aliases: ["iot", "device dashboard", "sensor", "telemetry", "pest control"],
    navigation: "device rail with map, alerts, fleet and analytics modes",
    hero: "live global fleet map and critical telemetry summary",
    composition: "map-first command canvas with collapsible detail panels",
    sectionOrder: "critical alerts, live map, fleet health, telemetry, jobs, reports",
    typography: "technical sans with mono device values and coordinates",
    palette: "deep navy, cyan telemetry, green online, amber warning and red alarm",
    spacing: "dense command layout with strong alert separation",
    cards: "device, sensor, gateway and alert panels",
    buttons: "acknowledge, dispatch, pair and diagnose command hierarchy",
    forms: "QR pairing, Wi-Fi setup and technician workflow controls",
    borders: "luminous status edges and topology links",
    background: "dark geospatial field with subtle network grid",
    motion: "live map pulses, telemetry streams and alert arrival",
    effects3d: "globe, building and floor topology when data supports it",
    mobile: "alert-first field app with map and scan tabs",
    interactions: "map clustering, device drill-down, QR scan, pairing and alert acknowledgement",
    footer: "gateway, MQTT, sync and fleet connectivity status",
  }),
  family({
    id: "fashion-runway",
    name: "Fashion Runway",
    aliases: ["fashion", "runway", "beauty", "lookbook"],
    navigation: "minimal collection navigation with editorial overlays",
    hero: "full-bleed campaign image or runway film with sparse type",
    composition: "lookbook chapters, collection grids and dramatic crops",
    sectionOrder: "campaign, new collection, lookbook, craft story, editorial, shop",
    typography: "fashion display serif or sharp grotesk with narrow captions",
    palette: "collection-led tones anchored by black, white and skin-neutral hues",
    spacing: "dramatic image scale and gallery whitespace",
    cards: "frameless looks and product compositions",
    buttons: "minimal shop labels and circular gallery controls",
    forms: "discreet size, availability and client-service controls",
    borders: "rare hairline editorial separators",
    background: "campaign-led fields alternating light and dark",
    motion: "runway pans, image masks and look transitions",
    effects3d: "layered campaign photography and fabric depth",
    mobile: "vertical lookbook with thumb-safe shop sheet",
    interactions: "lookbook swipe, size selector and quick-view sheets",
    footer: "collection index, client services and social channels",
  }),
  family({
    id: "portfolio-gallery",
    name: "Portfolio Gallery",
    aliases: ["portfolio", "designer", "photographer", "studio"],
    navigation: "quiet project index with view-mode controls",
    hero: "personal statement paired with one defining work",
    composition: "art-directed project gallery with case-study transitions",
    sectionOrder: "introduction, selected work, case study, capabilities, recognition, contact",
    typography: "distinctive display face with neutral reading sans",
    palette: "artwork-led neutrals with a personal signature accent",
    spacing: "gallery-scale whitespace and varied project rhythm",
    cards: "frameless project plates with individual aspect ratios",
    buttons: "project arrows, index controls and bold contact action",
    forms: "minimal project-enquiry form",
    borders: "precise construction lines used selectively",
    background: "gallery field that adapts to featured work",
    motion: "project transitions, image pans and case-study reveals",
    effects3d: "stacked artwork planes and controlled tilt",
    mobile: "vertical project reel with persistent index access",
    interactions: "view switcher, project filter and immersive case studies",
    footer: "compact biography, availability and contact",
  }),
  family({
    id: "real-estate-luxury",
    name: "Real Estate Luxury",
    aliases: ["real estate", "property", "estate agent", "homes"],
    navigation: "property-search navigation with saved-list access",
    hero: "cinematic flagship property with immediate location search",
    composition: "image-led listings, neighbourhood stories and agent trust",
    sectionOrder: "search, featured property, neighbourhoods, services, agents, valuation",
    typography: "refined modern serif paired with practical listing sans",
    palette: "stone, warm white, charcoal and restrained property accent",
    spacing: "premium gallery rhythm with readable listing density",
    cards: "large property photography with structured price metadata",
    buttons: "search, book viewing, save and valuation action hierarchy",
    forms: "location, price, type and viewing controls with clear labels",
    borders: "architectural hairlines and subtle map dividers",
    background: "daylight neutral canvas with full-bleed property scenes",
    motion: "gallery pans, map-list transitions and saved-property feedback",
    effects3d: "property tours, floor plans and map depth when available",
    mobile: "map/list switcher with sticky search and viewing action",
    interactions: "faceted search, map clusters, saved homes and booking",
    footer: "offices, areas, regulation and valuation links",
  }),
  family({
    id: "automotive-performance",
    name: "Automotive Performance",
    aliases: ["automotive", "car", "vehicle", "motorsport"],
    navigation: "model-led performance navigation with configure action",
    hero: "full-bleed vehicle scene and decisive performance statement",
    composition: "cinematic model chapters alternating engineering and emotion",
    sectionOrder: "model reveal, performance, design, technology, variants, configure",
    typography: "wide performance display face with technical mono values",
    palette: "carbon black, metal, white and model-specific signal colour",
    spacing: "full-viewport pace with compact technical specifications",
    cards: "model plates, engineering modules and configuration trays",
    buttons: "strong configure and test-drive controls with directional motion",
    forms: "model configuration and dealer booking steps",
    borders: "chrome, carbon and precision technical lines",
    background: "dark cinematic roads, studio light and engineered surfaces",
    motion: "vehicle tracking shots, spec reveals and light sweeps",
    effects3d: "interactive vehicle rotation and material depth",
    mobile: "swipeable model story with sticky configure action",
    interactions: "model switcher, colour configurator and specification comparison",
    footer: "models, ownership, dealers and legal information",
  }),
  family({
    id: "banking-secure",
    name: "Banking Secure",
    aliases: ["banking", "bank", "finance", "fintech"],
    navigation: "secure account-aware header with personal and business modes",
    hero: "trust-led financial proposition paired with real product UI",
    composition: "disciplined financial journey with proof and calculators",
    sectionOrder: "value, accounts, product proof, calculator, security, application",
    typography: "confident sans with tabular numerals and accessible body copy",
    palette: "midnight navy, trustworthy blue, confirmation green and warm human accent",
    spacing: "compact data density with generous decision space",
    cards: "account, rate and transaction panels with exact hierarchy",
    buttons: "secure primary actions, comparison controls and clear secondary links",
    forms: "accessible financial forms with progress, review and consent states",
    borders: "subtle navy rules with strong focus and confirmation states",
    background: "clean trust canvas with restrained financial gradients",
    motion: "number transitions, chart reveals and security confirmations",
    effects3d: "product-card depth only; no distracting financial decoration",
    mobile: "balance and action priority with secure bottom navigation",
    interactions: "calculators, account comparison, transaction drill-down and secure application",
    footer: "regulation, protection, accessibility and support information",
  }),
] as const

function hash(value: string): number {
  let result = 2166136261
  for (let index = 0; index < value.length; index += 1) {
    result ^= value.charCodeAt(index)
    result = Math.imul(result, 16777619)
  }
  return result >>> 0
}

function normalized(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim()
}

export function selectDesignFamily(
  seed: string,
  requestedDirection: string[],
  requestedText = "",
): DesignFamily {
  const request = normalized(`${requestedText} ${requestedDirection.join(" ")}`)
  const explicit = DESIGN_FAMILIES
    .flatMap((candidate) => candidate.aliases.map((alias) => ({
      candidate,
      alias: normalized(alias),
    })))
    .filter(({ alias }) => request.includes(alias))
    .sort((left, right) => right.alias.length - left.alias.length)[0]
  if (explicit) return explicit.candidate
  return DESIGN_FAMILIES[hash(`${seed}|${request}`) % DESIGN_FAMILIES.length]
}

export function designFamilyBrief(value: DesignFamily): string[] {
  return [
    `Design engine: ${value.name} (${value.id})`,
    `Navigation: ${value.navigation}`,
    `Hero: ${value.hero}`,
    `Page composition: ${value.composition}`,
    `Required section order: ${value.sectionOrder}`,
    `Typography: ${value.typography}`,
    `Colour palette: ${value.palette}`,
    `Spacing: ${value.spacing}`,
    `Card geometry: ${value.cards}`,
    `Buttons: ${value.buttons}`,
    `Forms: ${value.forms}`,
    `Border system: ${value.borders}`,
    `Background: ${value.background}`,
    `Motion: ${value.motion}`,
    `3D treatment: ${value.effects3d}`,
    `Mobile layout: ${value.mobile}`,
    `Interactive sections: ${value.interactions}`,
    `Footer: ${value.footer}`,
  ]
}
