[env:foodsafety_mouse]
platform = libretiny
board = generic-bk7231n-qfn32-tuya
framework = arduino
monitor_speed = 115200

lib_deps =
  knolleary/PubSubClient@^2.8

build_flags =
  -D WIFI_SSID=\"\${sysenv.FS_WIFI_SSID}\"
  -D WIFI_PASSWORD=\"\${sysenv.FS_WIFI_PASSWORD}\"
  -D MQTT_HOST=\"\${sysenv.FS_MQTT_HOST}\"
  -D MQTT_PORT=\${sysenv.FS_MQTT_PORT}
  -D MQTT_USERNAME=\"\${sysenv.FS_MQTT_USERNAME}\"
  -D MQTT_PASSWORD=\"\${sysenv.FS_MQTT_PASSWORD}\"
  -D DEVICE_ID=\"\${sysenv.FS_DEVICE_ID}\"
