import { NextResponse } from "next/server"
import { sql } from "@/lib/db"
import { getSession } from "@/lib/auth"

function createDefaultProjectFiles(name: string, template: string) {
  return {
    "app/page.tsx": `export default function Page() {
  return (
    <main className="min-h-screen bg-black text-white">
      <section className="mx-auto max-w-6xl px-6 py-24">
        <h1 className="text-5xl font-bold">${name}</h1>
        <p className="mt-6 text-lg text-white/70">
          Built with MujeebProAI real project file system.
        </p>
      </section>
    </main>
  )
}
`,

    "app/layout.tsx": `import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "${name}",
  description: "Generated by MujeebProAI",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`,

    "backend/orders.php": `<?php
header("Content-Type: application/json");

echo json_encode([
  "success" => true,
  "message" => "Orders backend for ${name}"
]);
`,

    "python/ai.py": `def run_ai_task():
    return {
        "success": True,
        "message": "Python AI script for ${name}"
    }

if __name__ == "__main__":
    print(run_ai_task())
`,

    "components/Header.tsx": `export function Header() {
  return (
    <header className="border-b border-white/10 px-6 py-4">
      <strong>${name}</strong>
    </header>
  )
}
`,

    "lib/project.ts": `export const projectName = "${name}"
export const projectTemplate = "${template}"
`,

    "public/README.txt": `Public assets for ${name}
`,
  }
}

export async function POST(req: Request) {
  try {
    const session = await getSession()

    if (!session?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const body = await req.json().catch(() => ({}))

    const name =
      typeof body.name === "string" && body.name.trim()
        ? body.name.trim()
        : "Untitled Project"

    const template =
      typeof body.template === "string" && body.template.trim()
        ? body.template.trim()
        : "blank"

    const files = createDefaultProjectFiles(name, template)

    const rows = await sql`
      INSERT INTO projects (user_id, name, template, files)
      VALUES (${session.id}::uuid, ${name}, ${template}, ${JSON.stringify(files)}::jsonb)
      RETURNING id, user_id, name, template, files, created_at, updated_at
    `

    return NextResponse.json({
      success: true,
      project: rows[0],
    })
  } catch (error) {
    console.error("Create project error:", error)
    return NextResponse.json(
      { error: "Failed to create project" },
      { status: 500 }
    )
  }
}
