"use client"

import { useEffect, useMemo, useRef, useState } from "react"
import { useRouter } from "next/navigation"
import {
  Code2,
  FolderKanban,
  GripVertical,
  Loader2,
  Monitor,
  Paperclip,
  Plus,
  Rocket,
  Send,
  Smartphone,
  Tablet,
  Volume2,
  VolumeX,
  Wand2,
} from "lucide-react"
import { useAuth } from "@/contexts/auth-context"
import type {
  SevenEightSixProject,
  SevenEightSixProjectFileMap,
} from "@/lib/786-admin/local-project-generator"
import type {
  AdminMessage,
  AdminProjectPreviewState,
  AdminProjectWithData,
} from "@/lib/786-admin/types"

const ADMIN_EMAIL = "mujeeb@job4u.com"
const CHAT_WIDTH_KEY = "786chat_admin_chat_width_v1"
const ACTIVE_PROJECT_ID_KEY = "786chat_admin_active_project_id_v1"
const ACTIVE_FILE_KEY = "786chat_admin_active_file_v1"
const SOUND_KEY = "786chat_admin_sound_v1"
const MODE_KEY = "786chat_admin_mode_v1"
const DEVICE_KEY = "786chat_admin_device_v1"

type Mode = "auto" | "deepseek-flash" | "deepseek-pro" | "gemini-flash" | "gemini-pro"
type Panel = "preview" | "code"
type Device = "desktop" | "tablet" | "mobile"
type UiMessage = {
  id: string
  role: "user" | "assistant"
  content: string
  model?: string | null
  reason?: string | null
  ts?: number
}
type ActiveProject = {
  id: string
  title: string
  description: string
  prompt: string
  files: SevenEightSixProjectFileMap
  preview_state: AdminProjectPreviewState
}

const MODE_LABEL: Record<Mode, string> = {
  auto: "Auto",
  "deepseek-flash": "DeepSeek Flash",
  "deepseek-pro": "DeepSeek Pro",
  "gemini-flash": "Gemini Flash",
  "gemini-pro": "Gemini Pro",
}

function uiFromAdminMessage(m: AdminMessage): UiMessage {
  return {
    id: m.id,
    role: m.role === "system" ? "assistant" : m.role,
    content: m.content,
    model: m.model,
    reason: m.reason,
    ts: m.created_at ? new Date(m.created_at).getTime() : undefined,
  }
}

function escapeHtml(value: string): string {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

function slugifyTitle(t: string): string {
  return (
    (t || "untitled")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "untitled"
  )
}

function formatTime(ts?: number): string {
  if (!ts) return ""
  return new Date(ts).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })
}

function classifyFile(path: string) {
  if (/^(src\/)?app\/page\.(tsx?|jsx?)$/.test(path)) return "page"
  if (/^(src\/)?app\/layout\.(tsx?|jsx?)$/.test(path)) return "layout"
  if (/^(src\/)?components\//.test(path)) return "component"
  if (/^(src\/)?(lib|utils|helpers|hooks|data|constants|types)\//.test(path)) return "lib"
  if (/\.css$/.test(path)) return "style"
  return "other"
}

function extractQuotedText(source: string): string[] {
  const texts = new Set<string>()
  const jsxText = Array.from(source.matchAll(/>([^<>{}\n][^<>{}\n]{2,160})</g)).map((m) => m[1])
  const quoted = Array.from(source.matchAll(/["'`]([^"'`]{4,140})["'`]/g)).map((m) => m[1])

  for (const raw of [...jsxText, ...quoted]) {
    const text = raw
      .replace(/\$\{[^}]+\}/g, "")
      .replace(/\s+/g, " ")
      .trim()
    if (!text) continue
    if (/^(use client|use server|className|return|export default|import )/i.test(text)) continue
    if (/^[#./@:_\-[\](),.%\d\s]+$/.test(text)) continue
    if (text.length < 4 || text.length > 150) continue
    texts.add(text)
  }

  return Array.from(texts)
}

function extractSections(files: SevenEightSixProjectFileMap): string[] {
  const text = Object.entries(files)
    .filter(([path]) => /\.(tsx?|jsx?)$/.test(path) && !/layout\.(tsx?|jsx?)$/.test(path))
    .map(([, value]) => String(value || ""))
    .join("\n")
  return extractQuotedText(text)
}

function buildPreviewHtml(project: ActiveProject): string {
  const page = String(
    project.files["app/page.tsx"] ||
      project.files["app/page.jsx"] ||
      project.files["src/app/page.tsx"] ||
      project.files["src/app/page.jsx"] ||
      ""
  )
  const css = String(project.files["app/globals.css"] || project.files["src/app/globals.css"] || "")
    .replace(/@tailwind\s+[a-z]+\s*;?/gi, "")
    .trim()

  const texts = extractSections(project.files)
  const likelyTitle =
    texts.find((t) => /restaurant|dashboard|quiz|login|calculator|website|app|fork|golden|saas|shop|agency/i.test(t)) ||
    project.title ||
    "Generated Project"
  const description =
    texts.find((t) => t !== likelyTitle && t.length >= 24) ||
    project.description ||
    "A real project generated by 786.Chat and saved in Neon."
  const nav = texts.filter((t) => t.length <= 18).slice(0, 5)
  const cards = texts.filter((t) => t !== likelyTitle && t !== description && t.length > 8).slice(0, 8)
  const slug = slugifyTitle(project.title)
  const fileCount = Object.keys(project.files || {}).length

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<script src="https://cdn.tailwindcss.com"></script>
<style>${css}</style>
<style>
html,body{margin:0;min-height:100%;background:#020617;color:white;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;}
*{box-sizing:border-box}
.preview-shell{min-height:100vh;background:radial-gradient(circle at top left,rgba(34,211,238,.22),transparent 35%),radial-gradient(circle at top right,rgba(168,85,247,.22),transparent 36%),linear-gradient(135deg,#020617,#0f172a 60%,#111827);}
.glass{border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.08);backdrop-filter:blur(18px);box-shadow:0 24px 70px rgba(0,0,0,.35)}
</style>
</head>
<body>
<main class="preview-shell">
  <section class="mx-auto flex min-h-screen max-w-7xl flex-col px-6 py-8">
    <nav class="glass flex items-center justify-between rounded-full px-6 py-4">
      <div class="text-lg font-black tracking-[.24em] text-cyan-200">${escapeHtml(project.title || "786.CHAT")}</div>
      <div class="hidden gap-6 text-sm font-bold text-slate-300 md:flex">
        ${(nav.length ? nav : ["Home", "Menu", "Booking", "Contact"]).map((item) => `<span>${escapeHtml(item)}</span>`).join("")}
      </div>
    </nav>

    <div class="grid flex-1 items-center gap-12 py-16 lg:grid-cols-[1.1fr_.9fr]">
      <div>
        <p class="mb-5 inline-flex rounded-full border border-cyan-300/30 bg-cyan-300/10 px-4 py-2 text-xs font-black uppercase tracking-[.3em] text-cyan-200">Live Neon Preview</p>
        <h1 class="max-w-5xl text-5xl font-black leading-tight tracking-tight md:text-7xl lg:text-8xl">${escapeHtml(likelyTitle)}</h1>
        <p class="mt-6 max-w-3xl text-lg leading-8 text-slate-300 md:text-xl">${escapeHtml(description)}</p>
        <div class="mt-10 flex flex-wrap gap-4">
          <a href="#sections" class="rounded-full bg-cyan-300 px-7 py-4 font-black text-slate-950 shadow-[0_0_45px_rgba(34,211,238,.32)]">Explore Project</a>
          <a href="#source" class="rounded-full border border-white/15 bg-white/10 px-7 py-4 font-black text-white">View Source Summary</a>
        </div>
      </div>

      <div class="glass rounded-[2.5rem] p-6">
        <div class="rounded-[2rem] bg-black/35 p-6">
          <div class="mb-6 flex gap-2"><span class="h-3 w-3 rounded-full bg-red-400"></span><span class="h-3 w-3 rounded-full bg-yellow-400"></span><span class="h-3 w-3 rounded-full bg-emerald-400"></span></div>
          <p class="text-xs font-black uppercase tracking-[.22em] text-cyan-200">786.chat/${escapeHtml(slug)}</p>
          <h2 class="mt-4 text-3xl font-black">Generated Website Preview</h2>
          <p class="mt-4 leading-7 text-slate-300">This preview is rendered directly from the saved project files so it never hangs on a runtime loader.</p>
          <div class="mt-6 grid grid-cols-2 gap-3">
            <div class="rounded-2xl bg-white/10 p-4"><div class="text-3xl font-black text-cyan-200">${fileCount}</div><div class="text-xs uppercase tracking-wider text-slate-400">Files</div></div>
            <div class="rounded-2xl bg-white/10 p-4"><div class="text-3xl font-black text-emerald-200">Live</div><div class="text-xs uppercase tracking-wider text-slate-400">Status</div></div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="sections" class="border-t border-white/10 px-6 py-20">
    <div class="mx-auto max-w-7xl">
      <h2 class="text-4xl font-black">Generated Sections</h2>
      <div class="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
        ${(cards.length ? cards : ["Hero Section", "Features", "Interactive Layout", "Contact"])
          .map(
            (card) =>
              `<article class="glass rounded-[2rem] p-6 transition hover:-translate-y-1"><h3 class="text-xl font-black">${escapeHtml(card)}</h3><p class="mt-3 leading-7 text-slate-300">Generated from real source files stored in Neon.</p></article>`
          )
          .join("")}
      </div>
    </div>
  </section>

  <section id="source" class="border-t border-white/10 px-6 py-12 text-sm text-slate-400">
    <div class="mx-auto max-w-7xl">Preview source: ${escapeHtml(Object.keys(project.files || {}).slice(0, 8).join(", "))}</div>
  </section>
</main>
<script>try{parent.postMessage({type:'786-preview-ready'},'*')}catch(e){}</script>
</body>
</html>`
}

function groupFiles(paths: string[]) {
  const groups = new Map<string, string[]>()
  for (const p of paths.sort()) {
    const folder = p.includes("/") ? p.split("/")[0] : "/"
    groups.set(folder, [...(groups.get(folder) || []), p])
  }
  return Array.from(groups.entries()).map(([folder, files]) => ({ folder, files }))
}

export default function SevenEightSixAdminChatPage() {
  const router = useRouter()
  const { user, isLoading } = useAuth()
  const [messages, setMessages] = useState<UiMessage[]>([])
  const [project, setProject] = useState<ActiveProject | null>(null)
  const [selectedFile, setSelectedFile] = useState("app/page.tsx")
  const [input, setInput] = useState("")
  const [mode, setMode] = useState<Mode>("auto")
  const [panel, setPanel] = useState<Panel>("preview")
  const [device, setDevice] = useState<Device>("desktop")
  const [sending, setSending] = useState(false)
  const [sound, setSound] = useState(true)
  const [chatWidth, setChatWidth] = useState(430)
  const [isResizing, setIsResizing] = useState(false)
  const endRef = useRef<HTMLDivElement | null>(null)

  const isAdmin = useMemo(() => user?.email?.toLowerCase().trim() === ADMIN_EMAIL, [user])
  const fileNames = useMemo(() => Object.keys(project?.files || {}), [project])
  const fileGroups = useMemo(() => groupFiles(fileNames), [fileNames])
  const previewHtml = useMemo(() => (project ? buildPreviewHtml(project) : ""), [project])
  const selectedSource = project?.files?.[selectedFile] || ""

  useEffect(() => {
    if (!isLoading && !isAdmin) router.replace("/786-admin/login")
  }, [isLoading, isAdmin, router])

  useEffect(() => {
    try {
      const saved = Number(localStorage.getItem(CHAT_WIDTH_KEY))
      if (saved >= 360 && saved <= 620) setChatWidth(saved)
      const savedSound = localStorage.getItem(SOUND_KEY)
      if (savedSound === "off") setSound(false)
      const savedMode = localStorage.getItem(MODE_KEY) as Mode | null
      if (savedMode && savedMode in MODE_LABEL) setMode(savedMode)
      const savedDevice = localStorage.getItem(DEVICE_KEY) as Device | null
      if (savedDevice === "desktop" || savedDevice === "tablet" || savedDevice === "mobile") setDevice(savedDevice)
    } catch {}
  }, [])

  useEffect(() => {
    try { localStorage.setItem(CHAT_WIDTH_KEY, String(Math.round(chatWidth))) } catch {}
  }, [chatWidth])
  useEffect(() => {
    try { localStorage.setItem(SOUND_KEY, sound ? "on" : "off") } catch {}
  }, [sound])
  useEffect(() => {
    try { localStorage.setItem(MODE_KEY, mode) } catch {}
  }, [mode])
  useEffect(() => {
    try { localStorage.setItem(DEVICE_KEY, device) } catch {}
  }, [device])
  useEffect(() => {
    try { localStorage.setItem(ACTIVE_FILE_KEY, selectedFile) } catch {}
  }, [selectedFile])
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }) }, [messages.length, sending])

  useEffect(() => {
    if (!isAdmin) return
    let cancelled = false
    async function hydrate() {
      let activeId: string | null = null
      try { activeId = localStorage.getItem(ACTIVE_PROJECT_ID_KEY) } catch {}
      if (!activeId) return
      try {
        const res = await fetch(`/api/786-admin/projects/${activeId}`, { cache: "no-store" })
        if (!res.ok) {
          if (res.status === 404) localStorage.removeItem(ACTIVE_PROJECT_ID_KEY)
          return
        }
        const json = (await res.json()) as { project: AdminProjectWithData }
        if (cancelled || !json.project) return
        const p = json.project
        const files = p.files || {}
        const initialFile =
          (p.preview_state?.active_file as string | undefined) ||
          (files["app/page.tsx"] ? "app/page.tsx" : Object.keys(files)[0]) ||
          "app/page.tsx"
        setProject({
          id: p.id,
          title: p.title,
          description: p.description,
          prompt: p.prompt,
          files,
          preview_state: p.preview_state || {},
        })
        setMessages((p.messages || []).map(uiFromAdminMessage))
        setSelectedFile(initialFile)
      } catch {}
    }
    hydrate()
    return () => { cancelled = true }
  }, [isAdmin])

  useEffect(() => {
    if (!isResizing) return
    const move = (e: MouseEvent) => setChatWidth(Math.min(Math.max(e.clientX - 92, 360), 620))
    const up = () => setIsResizing(false)
    document.body.style.cursor = "col-resize"
    document.body.style.userSelect = "none"
    window.addEventListener("mousemove", move)
    window.addEventListener("mouseup", up)
    return () => {
      document.body.style.cursor = ""
      document.body.style.userSelect = ""
      window.removeEventListener("mousemove", move)
      window.removeEventListener("mouseup", up)
    }
  }, [isResizing])

  function tone(done = false) {
    if (!sound) return
    try {
      const Ctx = window.AudioContext || (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext
      if (!Ctx) return
      const ctx = new Ctx()
      const gain = ctx.createGain()
      gain.connect(ctx.destination)
      gain.gain.value = 0.05
      ;(done ? [523, 659, 784] : [392, 523]).forEach((freq, i) => {
        const osc = ctx.createOscillator()
        osc.frequency.value = freq
        osc.connect(gain)
        osc.start(ctx.currentTime + i * 0.08)
        osc.stop(ctx.currentTime + i * 0.08 + 0.12)
      })
      setTimeout(() => ctx.close().catch(() => undefined), 600)
    } catch {}
  }

  function newChat() {
    setMessages([])
    setProject(null)
    setSelectedFile("app/page.tsx")
    setInput("")
    setPanel("preview")
    try {
      localStorage.removeItem(ACTIVE_PROJECT_ID_KEY)
      localStorage.removeItem(ACTIVE_FILE_KEY)
    } catch {}
    tone(true)
  }

  async function persistAfterGeneration(
    generated: SevenEightSixProject,
    userText: string,
    assistantText: string,
    assistantModel: string | null,
    assistantReason: string | null
  ) {
    const activeFile = (generated.files?.["app/page.tsx"] ? "app/page.tsx" : Object.keys(generated.files || {})[0]) || "app/page.tsx"
    const projectId = project?.id || null
    const url = projectId ? `/api/786-admin/projects/${projectId}` : "/api/786-admin/projects"
    const method = projectId ? "PATCH" : "POST"
    const body: Record<string, unknown> = {
      prompt: userText,
      preview_state: { active_file: activeFile, entry_path: "app/page.tsx" },
      files: generated.files,
      messages: [
        { role: "user", content: userText },
        { role: "assistant", content: assistantText, model: assistantModel, reason: assistantReason },
      ],
    }
    if (!projectId) {
      body.title = generated.title
      body.description = generated.description
    }
    const res = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) })
    if (!res.ok) return null
    const json = (await res.json()) as { project: AdminProjectWithData }
    const saved = json.project
    try { localStorage.setItem(ACTIVE_PROJECT_ID_KEY, saved.id) } catch {}
    return {
      id: saved.id,
      title: saved.title,
      description: saved.description,
      prompt: saved.prompt,
      files: saved.files || {},
      preview_state: saved.preview_state || {},
    }
  }

  async function send() {
    const text = input.trim()
    if (!text || sending) return
    setMessages((old) => [...old, { id: `u-${Date.now()}`, role: "user", content: text, ts: Date.now() }])
    setInput("")
    setSending(true)
    setPanel("preview")
    tone(false)

    try {
      const existingPayload = project
        ? {
            title: project.title,
            description: project.description,
            fileTree: Object.keys(project.files || {}),
            keyFiles: Object.fromEntries(
              (["app/page.tsx", "app/layout.tsx", "app/globals.css", "README.md"] as const)
                .filter((p) => typeof project.files?.[p] === "string")
                .map((p) => [p, project.files[p]])
            ),
          }
        : undefined

      const res = await fetch("/api/786-admin/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: text, mode, projectId: project?.id ?? null, existing: existingPayload }),
      })
      const json = await res.json()
      if (!res.ok || !json.success || !json.project) throw new Error(json.error || "Project generation failed.")
      const generated = json.project as SevenEightSixProject
      const assistantText = json.response || `Created project: ${generated.title}\nFiles: ${Object.keys(generated.files).length}`
      const persisted = await persistAfterGeneration(generated, text, assistantText, json.model ?? null, json.reason ?? null)
      if (!persisted) throw new Error("Project was generated but could not be saved to Neon.")
      setProject(persisted)
      setMessages((old) => [
        ...old,
        {
          id: `a-${Date.now()}`,
          role: "assistant",
          content: assistantText,
          model: json.model ?? null,
          reason: json.reason ?? null,
          ts: Date.now(),
        },
      ])
      setSelectedFile((persisted.preview_state.active_file as string | undefined) || (persisted.files["app/page.tsx"] ? "app/page.tsx" : Object.keys(persisted.files)[0]) || "app/page.tsx")
      tone(true)
    } catch (error) {
      setMessages((old) => [
        ...old,
        { id: `e-${Date.now()}`, role: "assistant", content: error instanceof Error ? error.message : "Request failed.", ts: Date.now() },
      ])
      tone(false)
    } finally {
      setSending(false)
    }
  }

  if (isLoading || !isAdmin) {
    return <main className="flex min-h-screen items-center justify-center bg-[#050713] text-white"><Loader2 className="h-8 w-8 animate-spin text-cyan-200" /></main>
  }

  return (
    <main className="h-screen overflow-hidden bg-[#050713] text-white">
      <div className="flex h-full">
        <aside className="hidden w-[92px] shrink-0 flex-col items-center gap-3 border-r border-cyan-300/15 bg-[#06101c] pt-24 lg:flex">
          <button onClick={() => router.push("/786-admin/projects")} className="grid h-12 w-12 place-items-center rounded-2xl border border-cyan-300/25 bg-cyan-300/10 text-cyan-100" title="Projects">
            <FolderKanban className="h-5 w-5" />
          </button>
        </aside>

        <section className="relative flex h-full min-w-[360px] shrink-0 flex-col border-r border-cyan-300/20 bg-[#081322]" style={{ width: chatWidth }}>
          <header className="flex h-[70px] shrink-0 items-center justify-between gap-3 border-b border-white/10 px-4">
            <button onClick={newChat} className="inline-flex items-center gap-2 rounded-2xl border border-emerald-300/35 bg-emerald-400/15 px-4 py-2.5 text-sm font-black text-emerald-50 transition hover:bg-emerald-400/25">
              <Plus className="h-4 w-4" /> New Chat
            </button>
            <div className="flex items-center gap-2">
              <button onClick={() => setSound((v) => !v)} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.045] px-3 py-2 text-xs font-bold text-slate-200">
                {sound ? <Volume2 className="h-3.5 w-3.5 text-emerald-300" /> : <VolumeX className="h-3.5 w-3.5 text-slate-500" />}
                Sound {sound ? "On" : "Off"}
              </button>
              <select value={mode} onChange={(e) => setMode(e.target.value as Mode)} className="w-[120px] rounded-xl border border-cyan-300/15 bg-[#101827] px-3 py-2 text-xs font-bold text-cyan-100">
                {Object.entries(MODE_LABEL).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
              </select>
            </div>
          </header>

          <div className="flex-1 overflow-y-auto px-4 py-5 pb-44">
            {messages.length === 0 ? (
              <div className="flex h-full items-center justify-center text-center text-slate-500">
                <div className="mx-auto max-w-[300px]"><p className="text-xl font-semibold text-cyan-100/90">Welcome back to 786.Chat</p><p className="mt-3 text-sm leading-6 text-slate-400">Start a new chat or open a saved project.</p></div>
              </div>
            ) : (
              messages.map((m) => {
                const isUser = m.role === "user"
                return (
                  <div key={m.id} className={`mb-4 flex ${isUser ? "justify-end" : "justify-start"}`}>
                    <div className={`max-w-[88%] rounded-3xl border p-4 text-sm leading-6 ${isUser ? "border-cyan-300/20 bg-cyan-300/10 text-cyan-50" : "border-white/10 bg-white/[0.045] text-slate-200"}`}>
                      <div className="mb-2 flex items-center justify-between gap-3 text-[11px] font-bold uppercase tracking-wider text-slate-400"><span>{isUser ? "You" : "786.Chat"}</span><span>{m.model || formatTime(m.ts)}</span></div>
                      <p className="whitespace-pre-wrap">{m.content}</p>
                      {m.reason && <p className="mt-3 rounded-xl border border-purple-300/15 bg-purple-400/5 p-3 text-xs leading-6 text-purple-200/80">{m.reason}</p>}
                    </div>
                  </div>
                )
              })
            )}
            {sending && <div className="mr-8 flex items-center gap-3 rounded-3xl border border-cyan-300/20 bg-cyan-300/10 p-4"><Wand2 className="h-5 w-5 animate-pulse text-cyan-200" /><span className="text-sm text-cyan-100">786.Chat is creating real project files…</span></div>}
            <div ref={endRef} />
          </div>

          <div className="absolute bottom-0 left-0 right-0 border-t border-white/10 bg-[#0a1322]/95 p-4 backdrop-blur-xl">
            <div className="flex gap-3 rounded-3xl border border-white/10 bg-[#162033] px-4 py-3">
              <Paperclip className="mt-2 h-5 w-5 shrink-0 text-slate-500" />
              <textarea value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send() } }} rows={1} className="min-h-10 flex-1 resize-none bg-transparent py-2 text-sm text-white outline-none placeholder:text-slate-500" placeholder={project ? `Update "${project.title}"…` : "Ask 786.Chat to build a real project…"} />
              <button onClick={send} disabled={sending || !input.trim()} className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-violet-600 transition hover:bg-violet-500 disabled:cursor-not-allowed disabled:opacity-50"><Send className="h-4 w-4" /></button>
            </div>
            <div className="mt-3 truncate rounded-2xl border border-cyan-400/20 bg-cyan-500/10 px-4 py-2 text-xs font-semibold text-cyan-100">{project ? `Editing project "${project.title}" — changes save to Neon.` : "New chat is empty. Your first prompt creates real files in Neon."}</div>
          </div>
        </section>

        <button type="button" onMouseDown={(e) => { e.preventDefault(); setIsResizing(true) }} className="hidden h-full w-4 shrink-0 cursor-col-resize items-center justify-center border-r border-cyan-300/15 bg-[#050713] lg:flex"><span className="flex h-24 w-2 items-center justify-center rounded-full border border-cyan-300/20 bg-cyan-300/10 text-cyan-100"><GripVertical className="h-5 w-5" /></span></button>

        <section className="flex min-w-0 flex-1 flex-col bg-[#030408]">
          <header className="flex h-[70px] shrink-0 items-center gap-3 border-b border-white/10 px-5">
            <div className="min-w-0 flex-1 rounded-full border border-white/10 bg-white/[0.045] px-4 py-2 text-sm text-slate-300"><span className="block truncate font-semibold">{project ? project.title : "New Chat"}</span></div>
            <button onClick={() => setPanel("preview")} className={`inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm font-bold ${panel === "preview" ? "bg-cyan-300 text-slate-950" : "border border-white/10 text-slate-400"}`}><Monitor className="h-4 w-4" />Preview</button>
            <button onClick={() => setPanel("code")} className={`inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm font-bold ${panel === "code" ? "bg-cyan-300 text-slate-950" : "border border-white/10 text-slate-400"}`}><Code2 className="h-4 w-4" />Code</button>
            {panel === "preview" && <div className="flex items-center gap-1 rounded-full border border-white/10 bg-white/[0.04] p-1"><button onClick={() => setDevice("desktop")} className={`rounded-full px-3 py-1.5 text-xs font-bold ${device === "desktop" ? "bg-cyan-300 text-slate-950" : "text-slate-400"}`}><Monitor className="h-3.5 w-3.5" /></button><button onClick={() => setDevice("tablet")} className={`rounded-full px-3 py-1.5 text-xs font-bold ${device === "tablet" ? "bg-cyan-300 text-slate-950" : "text-slate-400"}`}><Tablet className="h-3.5 w-3.5" /></button><button onClick={() => setDevice("mobile")} className={`rounded-full px-3 py-1.5 text-xs font-bold ${device === "mobile" ? "bg-cyan-300 text-slate-950" : "text-slate-400"}`}><Smartphone className="h-3.5 w-3.5" /></button></div>}
            <button className="rounded-full bg-cyan-300 px-5 py-2 text-sm font-black text-slate-950"><Rocket className="mr-2 inline h-4 w-4" />Publish</button>
          </header>

          {panel === "preview" ? (
            project && previewHtml ? (
              <div className={`min-h-0 flex-1 overflow-auto bg-[#030408] ${device === "desktop" ? "p-0" : "flex items-center justify-center p-6"}`}>
                <iframe srcDoc={previewHtml} title={`${project.title} preview`} sandbox="allow-scripts allow-forms allow-popups" className={device === "desktop" ? "h-full w-full border-0 bg-white" : device === "tablet" ? "h-[900px] w-[820px] max-h-full max-w-full rounded-[2rem] border border-cyan-300/25 bg-white shadow-2xl shadow-cyan-950/40" : "h-[844px] w-[390px] max-h-full max-w-full rounded-[2.5rem] border-[10px] border-slate-900 bg-white shadow-2xl shadow-cyan-950/40"} />
              </div>
            ) : sending ? (
              <div className="flex flex-1 items-center justify-center p-6 text-center text-cyan-100"><div className="rounded-2xl border border-cyan-300/20 bg-cyan-300/10 px-6 py-5 text-sm font-semibold">786.Chat is generating project files. Preview will render as soon as the project is saved.</div></div>
            ) : (
              <div className="flex flex-1 items-center justify-center p-6 text-center text-slate-500"><div className="flex min-h-full w-full items-center justify-center rounded-[2rem] border border-white/10 bg-[#0b111d]"><div><Monitor className="mx-auto mb-4 h-10 w-10 text-cyan-200" /><h2 className="text-xl font-black text-slate-300">No Preview Yet</h2><p className="mt-2 text-sm">Open a saved project or create a new one.</p></div></div></div>
            )
          ) : (
            <div className="grid min-h-0 flex-1 grid-cols-[260px_1fr] bg-[#1e1e1e]">
              <div className="min-h-0 overflow-auto border-r border-black/40 bg-[#181818] p-2"><div className="mb-2 px-3 pt-2 text-[10px] font-black uppercase tracking-[0.18em] text-slate-500">Explorer</div>{fileNames.length === 0 ? <p className="p-3 text-sm text-slate-500">No files yet.</p> : fileGroups.map(({ folder, files }) => <div key={folder} className="mb-3"><div className="px-2 py-1 text-[11px] font-bold uppercase tracking-wider text-slate-500">{folder}</div>{files.map((file) => { const kind = classifyFile(file); return <button key={file} onClick={() => setSelectedFile(file)} className={`mb-0.5 flex w-full items-center gap-2 rounded px-2 py-1 text-left text-[12px] ${selectedFile === file ? "bg-[#37373d] text-white" : "text-slate-300 hover:bg-white/[0.04]"}`}><span className={`h-1.5 w-1.5 rounded-full ${kind === "page" ? "bg-cyan-400" : kind === "component" ? "bg-violet-400" : kind === "lib" ? "bg-emerald-400" : kind === "style" ? "bg-pink-400" : "bg-slate-500"}`} /><span className="truncate font-mono">{file}</span></button> })}</div>)}</div>
              <div className="min-h-0 overflow-hidden bg-[#1e1e1e]"><div className="flex h-9 items-center justify-between border-b border-black/40 bg-[#252526] px-4"><span className="font-mono text-[11px] text-slate-300">{selectedFile}</span><span className="text-[10px] uppercase tracking-[0.18em] text-slate-500">{selectedSource.split("\n").length} lines</span></div><pre className="h-[calc(100%-2.25rem)] overflow-auto whitespace-pre px-4 py-3 font-mono text-[12.5px] leading-[1.55] text-[#d4d4d4]"><code>{selectedSource || "Select a file."}</code></pre></div>
            </div>
          )}
        </section>
      </div>
    </main>
  )
}
