import { NextResponse } from "next/server"
import { sql } from "@/lib/db"
import { getSession } from "@/lib/auth"

function normalizeFiles(files: unknown): Record<string, string> {
  if (!files || typeof files !== "object" || Array.isArray(files)) return {}

  const output: Record<string, string> = {}

  for (const [path, value] of Object.entries(files as Record<string, unknown>)) {
    if (typeof path === "string" && typeof value === "string") {
      output[path] = value
    }
  }

  return output
}

async function getProjectId(params: { id: string } | Promise<{ id: string }>) {
  const resolvedParams = await Promise.resolve(params)
  return String(resolvedParams.id || "")
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

function stripReactExpressions(value: string) {
  return value
    .replace(/\{\/\*[\s\S]*?\*\/\}/g, " ")
    .replace(/\{\s*[\w.]+\s*\?\s*["'`]([^"'`]+)["'`]\s*:\s*["'`]([^"'`]+)["'`]\s*\}/g, "$1")
    .replace(/\{`([^`]+)`\}/g, "$1")
    .replace(/\{"([^"]+)"\}/g, "$1")
    .replace(/\{'([^']+)'\}/g, "$1")
    .replace(/\{[^{}]*\}/g, " ")
}

function extractTextFromJsx(value: string) {
  return stripReactExpressions(value)
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim()
}

function extractFirstMatch(source: string, patterns: RegExp[]) {
  for (const pattern of patterns) {
    const match = source.match(pattern)
    if (match?.[1]) {
      const text = extractTextFromJsx(match[1])
      if (text) return text
    }
  }

  return ""
}

function getFile(files: Record<string, string>, possiblePaths: string[]) {
  for (const path of possiblePaths) {
    if (files[path]) return files[path]
  }

  return ""
}

function findComponentFile(files: Record<string, string>, name: string) {
  const exact = files[`components/${name}.tsx`] || files[`components/${name}.jsx`]
  if (exact) return exact

  const lowerName = name.toLowerCase()
  const path = Object.keys(files).find(
    (filePath) =>
      filePath.toLowerCase().includes(lowerName) &&
      /\.(tsx|jsx|ts|js)$/i.test(filePath)
  )

  return path ? files[path] || "" : ""
}

function extractCardsFromMenu(files: Record<string, string>) {
  const source =
    findComponentFile(files, "MenuSection") ||
    findComponentFile(files, "Menu") ||
    Object.values(files).find((content) => content.includes("menuItems")) ||
    ""

  if (!source) return []

  const objectMatches = [...source.matchAll(/\{\s*name:\s*["'`]([^"'`]+)["'`][\s\S]*?price:\s*["'`]([^"'`]+)["'`][\s\S]*?desc:\s*["'`]([^"'`]+)["'`][\s\S]*?\}/g)]

  return objectMatches.slice(0, 6).map((match) => ({
    name: match[1],
    price: match[2],
    desc: match[3],
  }))
}

function buildPreviewHtml(files: Record<string, string>) {
  const pageCode = getFile(files, ["app/page.tsx", "app/page.jsx", "pages/index.tsx", "pages/index.jsx"])
  const heroCode = findComponentFile(files, "Hero") || pageCode
  const headerCode = findComponentFile(files, "Header")
  const aboutCode = findComponentFile(files, "AboutSection") || findComponentFile(files, "About")
  const contactCode = findComponentFile(files, "ContactSection") || findComponentFile(files, "Contact")
  const footerCode = findComponentFile(files, "Footer")
  const globalsCss = getFile(files, ["app/globals.css", "styles/globals.css", "globals.css"])

  const title =
    extractFirstMatch(heroCode, [
      /<h1[^>]*>([\s\S]*?)<\/h1>/i,
      /<span[^>]*className=["'][^"']*(?:text-transparent|bg-gradient|bg-clip-text)[^"']*["'][^>]*>([\s\S]*?)<\/span>/i,
      /(?:title|heading|headline)\s*[:=]\s*["'`]([^"'`]+)["'`]/i,
    ]) ||
    "Your Project Is Ready"

  const eyebrow =
    extractFirstMatch(heroCode, [
      /<span[^>]*>([\s\S]*?)<\/span>/i,
      /(?:eyebrow|badge|label)\s*[:=]\s*["'`]([^"'`]+)["'`]/i,
    ]) ||
    "AI Generated Website"

  const description =
    extractFirstMatch(heroCode, [
      /<p[^>]*>([\s\S]*?)<\/p>/i,
      /(?:description|subtitle)\s*[:=]\s*["'`]([^"'`]+)["'`]/i,
    ]) ||
    "A modern responsive project generated by MujeebProAI."

  const navItems =
    [...headerCode.matchAll(/["'`](Home|About|Menu|Services|Testimonials|Contact|Booking|Gallery)["'`]/gi)]
      .map((match) => match[1])
      .filter((value, index, array) => array.indexOf(value) === index)
      .slice(0, 6)

  const cards = extractCardsFromMenu(files)

  const aboutText =
    extractFirstMatch(aboutCode, [
      /<p[^>]*>([\s\S]*?)<\/p>/i,
      /(?:description|text)\s*[:=]\s*["'`]([^"'`]+)["'`]/i,
    ]) ||
    "Built with real project files, components, layout, and saved source code."

  const contactText =
    extractFirstMatch(contactCode || footerCode, [
      /<p[^>]*>([\s\S]*?)<\/p>/i,
      /(?:email|phone|address)\s*[:=]\s*["'`]([^"'`]+)["'`]/i,
    ]) ||
    "Ready for contact, booking, and backend integration."

  const navHtml = navItems.length
    ? navItems.map((item) => `<a href="#${item.toLowerCase()}" class="text-sm text-white/70 hover:text-amber-300">${escapeHtml(item)}</a>`).join("")
    : `<a href="#home" class="text-sm text-white/70 hover:text-amber-300">Home</a><a href="#menu" class="text-sm text-white/70 hover:text-amber-300">Menu</a><a href="#contact" class="text-sm text-white/70 hover:text-amber-300">Contact</a>`

  const cardsHtml = cards.length
    ? cards.map((card) => `
      <div class="rounded-3xl border border-white/10 bg-white/5 p-6 shadow-xl">
        <p class="text-amber-300 font-black">${escapeHtml(card.price)}</p>
        <h3 class="mt-2 text-xl font-bold">${escapeHtml(card.name)}</h3>
        <p class="mt-3 text-sm text-slate-300">${escapeHtml(card.desc)}</p>
      </div>
    `).join("")
    : `
      <div class="rounded-3xl border border-white/10 bg-white/5 p-6 shadow-xl"><h3 class="text-xl font-bold">Premium Feature</h3><p class="mt-3 text-slate-300">Created from real project files.</p></div>
      <div class="rounded-3xl border border-white/10 bg-white/5 p-6 shadow-xl"><h3 class="text-xl font-bold">Modern Design</h3><p class="mt-3 text-slate-300">Responsive layout with polished sections.</p></div>
      <div class="rounded-3xl border border-white/10 bg-white/5 p-6 shadow-xl"><h3 class="text-xl font-bold">Ready to Edit</h3><p class="mt-3 text-slate-300">Ask AI for precise file-based changes.</p></div>
    `

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<script src="https://cdn.tailwindcss.com"></script>
<style>
html, body { margin: 0; min-height: 100%; background: #050509; color: white; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
${globalsCss}
</style>
</head>
<body>
<main class="min-h-screen bg-black text-white overflow-hidden">
  <header class="fixed left-0 right-0 top-0 z-40 border-b border-white/10 bg-black/55 backdrop-blur-xl">
    <div class="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
      <div class="text-lg font-black tracking-tight text-amber-300">MujeebProAI Preview</div>
      <nav class="hidden items-center gap-6 md:flex">${navHtml}</nav>
      <a href="#contact" class="rounded-full bg-amber-400 px-5 py-2 text-sm font-bold text-black">Book Now</a>
    </div>
  </header>

  <section id="home" class="relative flex min-h-screen items-center justify-center overflow-hidden px-6 py-32">
    <div class="absolute inset-0 bg-gradient-to-br from-black via-zinc-950 to-amber-950"></div>
    <div class="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_rgba(245,158,11,0.18)_0%,_transparent_68%)]"></div>
    <div class="absolute left-10 top-24 h-32 w-32 animate-pulse rounded-full bg-amber-400/20 blur-3xl"></div>
    <div class="absolute bottom-24 right-16 h-48 w-48 animate-pulse rounded-full bg-orange-500/10 blur-3xl"></div>

    <div class="relative z-10 mx-auto max-w-5xl text-center">
      <p class="mb-6 inline-flex rounded-full border border-amber-300/30 bg-amber-300/10 px-4 py-2 text-xs font-semibold uppercase tracking-[0.3em] text-amber-300">
        ${escapeHtml(eyebrow)}
      </p>
      <h1 class="text-5xl font-black leading-tight tracking-tight md:text-7xl lg:text-8xl">
        <span class="bg-gradient-to-r from-amber-100 via-amber-400 to-orange-300 bg-clip-text text-transparent">${escapeHtml(title)}</span>
      </h1>
      <p class="mx-auto mt-6 max-w-3xl text-lg leading-relaxed text-zinc-300 md:text-xl">
        ${escapeHtml(description)}
      </p>
      <div class="mt-10 flex flex-wrap justify-center gap-4">
        <a href="#contact" class="rounded-full bg-gradient-to-r from-amber-400 to-amber-500 px-8 py-4 font-bold text-black shadow-2xl shadow-amber-500/25">Reserve a Table</a>
        <a href="#menu" class="rounded-full border border-white/15 bg-white/10 px-8 py-4 font-bold text-white backdrop-blur hover:bg-white/15">View Our Menu</a>
      </div>
    </div>
  </section>

  <section id="about" class="bg-black px-6 py-24">
    <div class="mx-auto max-w-5xl text-center">
      <p class="text-sm uppercase tracking-[0.3em] text-amber-300">About</p>
      <h2 class="mt-4 text-4xl font-black md:text-5xl">A premium experience</h2>
      <p class="mx-auto mt-6 max-w-3xl text-lg leading-relaxed text-zinc-400">${escapeHtml(aboutText)}</p>
    </div>
  </section>

  <section id="menu" class="bg-zinc-950 px-6 py-24">
    <div class="mx-auto max-w-6xl">
      <div class="mb-14 text-center">
        <p class="text-sm uppercase tracking-[0.3em] text-amber-300">Menu</p>
        <h2 class="mt-4 text-4xl font-black md:text-5xl">Featured selections</h2>
      </div>
      <div class="grid gap-6 md:grid-cols-3">${cardsHtml}</div>
    </div>
  </section>

  <section id="contact" class="bg-gradient-to-br from-amber-500 to-orange-700 px-6 py-24 text-black">
    <div class="mx-auto grid max-w-5xl gap-10 md:grid-cols-2 md:items-center">
      <div>
        <p class="text-sm font-bold uppercase tracking-[0.3em]">Contact</p>
        <h2 class="mt-4 text-4xl font-black md:text-5xl">Ready for customers</h2>
        <p class="mt-5 text-lg">${escapeHtml(contactText)}</p>
      </div>
      <div class="rounded-3xl bg-white/90 p-6 shadow-2xl">
        <div class="grid gap-4">
          <input class="rounded-xl border p-4" placeholder="Full name" />
          <input class="rounded-xl border p-4" placeholder="Email or phone" />
          <button class="rounded-xl bg-black p-4 font-bold text-white">Send Request</button>
        </div>
      </div>
    </div>
  </section>
</main>
</body>
</html>`
}

export async function GET(
  _req: Request,
  { params }: { params: { id: string } | Promise<{ id: string }> }
) {
  try {
    const session = await getSession()

    if (!session?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const projectId = await getProjectId(params)

    const rows = await sql`
      SELECT id, files
      FROM projects
      WHERE id = ${projectId}::uuid
        AND user_id = ${session.id}::uuid
        AND deleted_at IS NULL
      LIMIT 1
    `

    if (!rows.length) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 })
    }

    const files = normalizeFiles(rows[0].files)
    const html = buildPreviewHtml(files)

    return NextResponse.json(
      { success: true, html },
      { headers: { "Cache-Control": "no-store" } }
    )
  } catch (error) {
    console.error("Project preview error:", error)

    return NextResponse.json(
      {
        error: "Failed to build project preview",
        debug: error instanceof Error ? error.message : "Unknown preview error",
      },
      { status: 500, headers: { "Cache-Control": "no-store" } }
    )
  }
}
