const DEFAULT_REPOSITORY = "786-Chat/786-chat"
const DEFAULT_BASE_BRANCH = "main"

type GitHubRef = { object: { sha: string } }
type GitHubCommit = { tree: { sha: string } }
type GitHubBlob = { sha: string }
type GitHubTree = { sha: string }
type CreatedCommit = { sha: string }
type CreatedPullRequest = { html_url: string; number: number }

export type PublishedGeneratedProject = {
  branch: string
  commitSha: string
  pullRequestUrl: string
  pullRequestNumber: number
  directory: string
}

function requiredToken(): string {
  const value = process.env.GITHUB_BUILD_TOKEN?.trim()
  if (!value) throw new Error("GITHUB_BUILD_TOKEN is not configured")
  return value
}

function cleanSegment(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80)
}

async function githubRequest<T>(
  repository: string,
  path: string,
  init: RequestInit = {},
): Promise<T> {
  const response = await fetch(`https://api.github.com/repos/${repository}${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${requiredToken()}`,
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
      ...(init.headers || {}),
    },
    cache: "no-store",
  })

  if (!response.ok) {
    const detail = await response.text().catch(() => "")
    throw new Error(
      `GitHub publishing failed (${response.status})${detail ? `: ${detail.slice(0, 500)}` : ""}`,
    )
  }

  if (response.status === 204) return undefined as T
  return (await response.json()) as T
}

export async function publishGeneratedProjectToGitHub(input: {
  buildId: string
  projectId: string
  title: string
  sourceVersion: string
  files: Record<string, string>
}): Promise<PublishedGeneratedProject> {
  const repository = process.env.GITHUB_BUILD_REPOSITORY?.trim() || DEFAULT_REPOSITORY
  const baseBranch = process.env.GITHUB_GENERATED_BASE_BRANCH?.trim() || DEFAULT_BASE_BRANCH
  const projectSegment = cleanSegment(input.projectId) || "project"
  const buildSegment = cleanSegment(input.buildId).slice(0, 20) || Date.now().toString()
  const branch = `generated/${projectSegment}/${buildSegment}`
  const directory = `generated-projects/${projectSegment}`

  const baseRef = await githubRequest<GitHubRef>(
    repository,
    `/git/ref/heads/${encodeURIComponent(baseBranch)}`,
  )
  const baseCommit = await githubRequest<GitHubCommit>(
    repository,
    `/git/commits/${baseRef.object.sha}`,
  )

  const treeEntries: Array<{
    path: string
    mode: "100644"
    type: "blob"
    sha: string
  }> = []

  for (const [relativePath, content] of Object.entries(input.files)) {
    const blob = await githubRequest<GitHubBlob>(repository, "/git/blobs", {
      method: "POST",
      body: JSON.stringify({ content, encoding: "utf-8" }),
    })
    treeEntries.push({
      path: `${directory}/${relativePath}`,
      mode: "100644",
      type: "blob",
      sha: blob.sha,
    })
  }

  const manifest = JSON.stringify(
    {
      projectId: input.projectId,
      buildId: input.buildId,
      title: input.title,
      sourceVersion: input.sourceVersion,
      generatedBy: "786.chat",
      providers: ["DeepSeek", "Gemini"],
      createdAt: new Date().toISOString(),
    },
    null,
    2,
  )
  const manifestBlob = await githubRequest<GitHubBlob>(repository, "/git/blobs", {
    method: "POST",
    body: JSON.stringify({ content: manifest, encoding: "utf-8" }),
  })
  treeEntries.push({
    path: `${directory}/.786-chat-build.json`,
    mode: "100644",
    type: "blob",
    sha: manifestBlob.sha,
  })

  const tree = await githubRequest<GitHubTree>(repository, "/git/trees", {
    method: "POST",
    body: JSON.stringify({ base_tree: baseCommit.tree.sha, tree: treeEntries }),
  })
  const commit = await githubRequest<CreatedCommit>(repository, "/git/commits", {
    method: "POST",
    body: JSON.stringify({
      message: `build(786.chat): publish generated project ${input.title}`,
      tree: tree.sha,
      parents: [baseRef.object.sha],
    }),
  })

  await githubRequest<void>(repository, "/git/refs", {
    method: "POST",
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: commit.sha }),
  })

  const pullRequest = await githubRequest<CreatedPullRequest>(repository, "/pulls", {
    method: "POST",
    body: JSON.stringify({
      title: `Generated project: ${input.title}`,
      head: branch,
      base: baseBranch,
      draft: true,
      body: [
        "## Generated by 786.chat",
        "",
        `Project ID: \`${input.projectId}\``,
        `Build ID: \`${input.buildId}\``,
        `Source version: \`${input.sourceVersion}\``,
        "",
        `Files are isolated under \`${directory}/\` and must pass review before merge.`,
        "AI providers are restricted to DeepSeek and Gemini.",
      ].join("\n"),
    }),
  })

  return {
    branch,
    commitSha: commit.sha,
    pullRequestUrl: pullRequest.html_url,
    pullRequestNumber: pullRequest.number,
    directory,
  }
}
