ALTER TABLE products ADD COLUMN IF NOT EXISTS last_stock_in_date TIMESTAMPTZ;
ALTER TABLE products ADD COLUMN IF NOT EXISTS last_stock_out_date TIMESTAMPTZ;
ALTER TABLE products ADD COLUMN IF NOT EXISTS used_date DATE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS best_before_date DATE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS use_by_date DATE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS expiry_date DATE;
