from pathlib import Path

path = Path("lib/786-admin/codegen.ts")
source = path.read_text()
old = '''  // Project files are always generated by DeepSeek. Gemini is deliberately
  // limited to understanding attached images/files below so text-only builds
  // never consume Gemini quota or wait on a Gemini fallback.
  const generationMode: CodegenMode = mode === "deepseek-pro" ? "deepseek-pro" : "deepseek-flash"
  const picked = pickModel(generationMode, false)'''
new = '''  // Honour the provider selected by the outer controller. Auto remains
  // DeepSeek Flash, while an explicit Gemini fallback must actually execute
  // Gemini rather than being silently rewritten back to DeepSeek.
  const generationMode: CodegenMode = mode === "auto" ? "deepseek-flash" : mode
  const picked = pickModel(generationMode, attachments.length > 0)'''
if old not in source:
    raise SystemExit("expected provider-mode block not found")
source = source.replace(old, new)
path.write_text(source)
